name: bpftrace
version: 0-20181211-70c9c12db1
summary: high-level tracing language for Linux eBPF
description: 'BPFtrace is a high-level tracing language for Linux enhanced Berkeley Packet Filter available in recent Linux kernels. BPFtrace uses LLVM as a backend to compile scripts to BPF-bytecode and makes use of BCC for interacting with the Linux BPF system, as well as existing Linux tracing capabilities: kernel dynamic tracing, user-level dynamic tracing and tracepoints.'

confinement: strict
grade: stable

parts:
    bpftrace:
        plugin: cmake
        source: https://github.com/iovisor/bpftrace.git
        configflags:
            - '-DCMAKE_BUILD_TYPE=DEBUG'

        build-packages:
            - libc6
            - iperf
            - bison
            - cmake
            - flex
            - g++
            - libstdc++-dev
            - libelf-dev
            - zlib1g-dev
            - libfl-dev
            - clang-6.0
            - libclang-6.0-dev
            - libclang-common-6.0-dev
            - libclang1-6.0
            - libllvm6.0
            - llvm-6.0
            - llvm-6.0-dev
            - llvm-6.0-runtime

        stage-packages:
            - libelf-dev
            - libc6
            - libgcc-6-dev
            - libstdc++6
            - libtinfo-dev
            - libclang1-6.0
            - zlib1g
            - libbpfcc-dev

        prime:
            - bin/
            - lib/
            - usr/

apps:
    bpftrace:
        command: bpftrace
        plugs: [ system-trace ]
        environment:
            LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/x86-64-linux-gnu:$SNAP/usr/lib/x86-64-linux-gnu:$SNAP/usr/lib/gcc/x86_64-linux-gnu/6

