name: cppcheck
version: 1.76.1-20161118-15464-e94407f
summary: A tool for static C/C++ code analysis
description: Cppcheck is a static analysis tool for C/C++ code. Unlike C/C++ compilers and many other analysis tools it does not detect syntax errors in the code. Cppcheck primarily detects the types of bugs that the compilers normally do not detect.
confinement: strict

parts:
    cppcheck:
        plugin: make
        source: git://github.com/danmar/cppcheck
        make-parameters:
            - CFGDIR=/usr/share/cppcheck/cfg
        build-packages:
            - gcc
            - make
        snap:
            - usr/bin/cppcheck

apps:
    cppcheck:
        plugs: [home]
        command: usr/bin/cppcheck

